### ISSUE TITLE
Azure Portal Changes

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#11]
Azure Portal changes

The Azure Portal has the following and many more changes:

"+New" button is now "+ Create a resource" button
"More Services" button at the bottom of the menu is now "All Services" at the top
"Databases + Analytics" is now "Databases" and "Analytics"
"Azure Data Lake Store" is now "Azure Data Lake Storage Gen1"
Stream Analytics job inputs are split into "Add stream input" and "Add reference input". Both options have sub items. 
Steps to create an IoT hub is changed (wizard-like configuration)
You need an Office 365 trial account and make sure you are logged in to the Power BI portal and My Workspace is created.

Instructions will need to be updated accordingly.

**Comment by JohnPWSharp** [comment]
We have updated the lab and demo instructions (September 2018). We will keep them under review
