### ISSUE TITLE
Power BI averages on longitude and lattitude

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#14]
Arg Gis visual doesn't show any result because it averages the longitude and lattitude values by default.

![image](https://user-images.githubusercontent.com/10166617/42939957-f3613bf2-8b57-11e8-9077-1c731c01dff7.png)

**Comment by JohnPWSharp** [comment]
The lab has been updated
