### ISSUE TITLE
Module 2 Lab - Task 8

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#22]
I am teaching the course this week using Learn On Demand VM's and have experienced a problem when trying to run the patrol car device 2 solution. After editing the app.config and putting in the ServiceBusConnectionString and IoTHubConnectionString setting, when the start button is clicked the app starts and stays at the press ENTER to stop patrol cars. After a minute it times out and errors on the Visual Studio App and gives an error on the PatrolCars.cs line 39

this.subscriptionClient.OnMessage(message => chaseCar(message));

We found a solution by adding the following at line 36 and rebuilding the solution

ServiceBusEnvironment.SystemConnectivity.Mode = ConnectivityMode.Http;

This affected everyone on the class. I am not sure if the issue was with Learn On Demand blocking ports or Azure

**Comment by JohnPWSharp** [comment]
I have amended the project and added the suggested line of code. I have checked that it still works in the desktop VM environment

**Comment by molenaar** [comment]
Tried it severaLtime with the latest code and it still doesn't work.

**Comment by JohnPWSharp** [comment]
Are you using desktop VMs with the gateway VM (MT17B-WS2016-NAT) to connect to the outside world, or are you running using Learn On Demand?
