### ISSUE TITLE
Mod 3 File Missing

### ISSUE THREAD

**Issue by connect2puneett** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#23]
In Exercise No1 for Mod 3 StockData.txt file is missing from E:/DemoFile/Mod3. Due to which StockMarket Simulation app does not work.

**Comment by JohnPWSharp** [comment]
Can you clarify? The demos for module 3 do not use the stock market example - they simulate temperature devices

**Comment by JohnPWSharp** [comment]
My bad. I was looking at 20777! I will take a look at this issue for 20776 asap

**Comment by JohnPWSharp** [comment]
The problem was due to the trainingRun key in the AppSettings.config file. This should have been false initially, but was set to true. I have uploaded corrected version of this file.

**Comment by connect2puneett** [comment]
Hi John.
Hi have updated the App.config file, but the StockData.txt file missing file is still there.
When we run the StockMarketSimulation App in the StockMarketStateManager.cs file 

   public class StockMarketStateManager
    {
        private const string DATAFILE = @"E:\Demofiles\Mod03\StockData.txt";
        private static SortedList<int, StockPrice> stockData = null;

where you have the above code.

It asks for the StockData.txt, which is missing. 
Kindly help.

**Comment by fhe-fr** [comment]
Hi,
I have the same issue:
namespace StockMarketSimulation
{
    public class StockMarketStateManager
    {
        private const string DATAFILE = @"E:\Demofiles\Mod03\StockData.txt";
        private static SortedList<int, StockPrice> stockData = null;

The StockData.txt is missing.
Thanks
Regards

**Comment by connect2puneett** [comment]
Hi,

This is not an error, i actually realized later.

Once you run the stock market simulation, the stockdata file would be
created then.
