### ISSUE TITLE
Lab 3 - Issue

### ISSUE THREAD

**Issue by connect2puneett** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#24]
The LocationAlerts App of visual studio (app which shows the london map) fails. It starts initially but then gives an error saying Carid: value cannot be null

**Comment by JohnPWSharp** [comment]
Are you using the Learn on Demand environment? If so, then this could be the same problem (with fix) reported by Tony Cook (issue #22)

https://github.com/MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-/issues/22

**Comment by connect2puneett** [comment]
Hi John, 
I am not using the Learn on Demand. I am doing the labs on my Local system, and i am getting the error in LocationAlerts App for Mod 2 as well as Mod 3.

**Comment by connect2puneett** [comment]
Hi John

The issue with my LocationAlerts App. It abruptly stops saying carid, cannot be null. Can you please look into that.

Thanks

**Comment by connect2puneett** [comment]
Yes, John
I am running it from the E:\Labfiles\Lab03\LocationAlerts folder. I even tried to run it on Learn on Demand Setup still gives the same error (below)

Map.Page.Xaml.cs file has the below error.

System.ArgumentNullException: 'Value cannot be null.'


                            // If the patrol car already exists then just update its location
                            MapIcon car = (MapIcon)MapControl.MapElements.FirstOrDefault(m => String.Compare((m as MapIcon).Title, patrolCarData.CarID) == 0);
                            if (car != null)
                            {
                                car.Location = new Geopoint(patrolCarPosition);
                            }
                            // Otherwise create a new icon and add it to the map
                            else
                            {
                                car = new MapIcon();
                                car.Location = new Geopoint(patrolCarPosition);
                                car.NormalizedAnchorPoint = new Point(0.5, 1.0);
                                car.Title = patrolCarData.CarID;

**Comment by connect2puneett** [comment]
![image](https://user-images.githubusercontent.com/43827512/46475203-f4a26b00-c7f5-11e8-9180-1b1c1dd0f4b9.png)

**Comment by JohnPWSharp** [comment]
Can you drop and recreate the LocationAlerts queue in the Azure portal - it looks like there could be some junk that the app is reading, and this will not be deserialized correctly into a PatrolCar object. Make sure you have the correct values for ServiceBusEndpoint, and SASKey in the ConfigSettings.txt file

**Comment by JohnPWSharp** [comment]
Did this solve the problem?

**Comment by connect2puneett** [comment]
Hi John

Didn't got time to try. Wud check today and revert.

Thanks

**Comment by connect2puneett** [comment]
Hi John

I tried recreating the Job and tried the app from Mod 2 as well, but it still gives the same error.

Kindly Advise.

**Comment by JohnPWSharp** [comment]
Can you verify that you deleted the queue and recreated it, and that it only contains patrol car data. Try using Service Bus explorer (https://github.com/paolosalvatori/ServiceBusExplorer) to examine the queue. The body of a locationalert message should look like that shown in this image:

![image](https://user-images.githubusercontent.com/1889218/46599367-1d20b280-cadf-11e8-905a-4a9db3dbc2e7.png)
