### ISSUE TITLE
Issue with Missing File for Mod 3 StockData.txt

### ISSUE THREAD

**Issue by connect2puneett** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#25]
Hi have updated the App.config file, but the StockData.txt file missing file is still there.
When we run the StockMarketSimulation App in the StockMarketStateManager.cs file 

   public class StockMarketStateManager
    {
        private const string DATAFILE = @"E:\Demofiles\Mod03\StockData.txt";
        private static SortedList<int, StockPrice> stockData = null;

where you have the above code.

It asks for the StockData.txt, which is missing. 
Kindly help.

_Originally posted by @connect2puneett in https://github.com/MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-/issues/23#issuecomment-426979289_

**Comment by JohnPWSharp** [comment]
OK. To clarify. The **TrainingRun** setting in App.config  should be **true** (I have updated the config file again and put it back the way it was). In this mode, the app writes a list of stocks (ID, ticker, initial price) to the E:\Demofiles\Mod03\StockData.txt file. Later on in the demos, **TrainingRun** is set to **false**, and the simulation reads the initial stock tickers and prices back from this file (this is for repeatability - subsequent runs need to use the same set of tickers).

Make sure you are running using a configuration that matches the course setup. The Demofiles folder is expected to be on the **E: drive**. If you have placed it somewhere else, modify the following line in the StockMarketStateManager.cs file:

```C#
private const string DATAFILE = @"E:\Demofiles\Mod03\StockData.txt";
```

**Comment by connect2puneett** [comment]
Thanks a ton John. That Worked
