### ISSUE TITLE
Lab 6 CustomerOutputter Register Assembly missing

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#29]
Module 6, Exercise 2, task 2
For some students, right click Register Assembly doesn't show up for the CustomerOutputter project. It works for the CustomExtractors, however not for the CustomerOutputter.

What steps are possibly missing?

Marcel

**Comment by JohnPWSharp** [comment]
I have added some steps to use as a workaround for this problem in Exercise 1, Task 2.
