### ISSUE TITLE
The volume of data being sent to the streaming dataset is too high

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#4]
After creating the PowerBi tile in Module 2, exercise 1, Power BI reports:
"The volume of data being sent to the streaming dataset is too high. Please reduce the rate that data is being pushed to the streaming dataset and try again.See details"

**Comment by dscoombes** [comment]
If you get this error message, you could try reducing the number of patrol cars that are generating data. This is controlled by the NumCars setting in Allfiles\Lab02\PatrolCarDevice\PatrolCar\App.config.

**Comment by JohnPWSharp** [comment]
I have adjusted the default configuration of the apps sending data through to Power BI to reduce the likelihood of this problem recurring.
