### ISSUE TITLE
Markdown missing and/or incomplete in multiple Lab Guides & LAKs

### ISSUE THREAD

**Issue by karlwest99** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#5]
Will it be possible to clean up the markdown for the various Lab Guides and also LAKs in 20776?  In nearly all of the modules, there appear to be various errors and/or omissions of the .md files that have the effect of rendering many important portions of the instructions/LAKs into a less-then-readable format.

**Comment by dscoombes** [comment]
Could you list the specific issues that you've noticed? I can see that italics within bold (**bold_italic_**) has not converted properly; please let me know what else needs fixing.

**Comment by karlwest99** [comment]
Regardless of which browser I use (Edge, IE11, Opera, Firefox-- or
alternatively, if I try and download the raw .md to utilize a local
markdown viewer) once you scroll down to an affected section one sees the
formatting end, to be replaced by what becomes essentially a 'wall of
unformatted single spaced text'.

Depending on browser in use, you may or may not be able to scroll within
the text to see all of it, and other portions will have some formatting
tags appear in a raw format that is confusing.  i.e.  "...1. Switch to the
Azure portal, click **All resources**, and then click **adls*&lt;your name
&gt;&lt;date&gt;***.

See also screenshot below - the section highlighted in yellow is an example
of the issue.  It also appears that immediately previous to the highlighted
section there is an additional formatting glitch causing the query SELECT
statement from Task 5/Step 1 to be split into several unexpected text boxes
as well.  Perhaps a formatting glitch/error at this point is the root-cause
of the problem?  (I am not an .md markdown expert, unfortunately)

Regarding other locations this issue exists - it can be seen in LAK 2, 3,
4, 5, & 8, as well as the Student instructions in 3, 4, 5, 6, 8. (possibly
other sections as well - it is easy to verify by simply using a browser to
browse through each guide/lak to look for this issue)



​
While it is possible to 'workaround' the issue manually by attempting to
format these instructions/LAKs separately onsite, it would seem highly
desirable to insure the formatting is as expected.

**Comment by karlwest99** [comment]
BTW, thanks for fixing this - issue resolved.
