### ISSUE TITLE
Build catalog

### ISSUE THREAD

**Issue by ImportantNotice** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#8]
Please include catalog Build.

**Comment by sho74** [comment]
Confirm epsonce of BUILD catalog.

**Comment by ImportantNotice** [comment]
Hi,
I confirm absence of BUILD catalog ,
only AllFiles and Instructions.



Regards, Vladislavas Petkevic

The labs are stored on GitHub in a repo. The structure for each Microsoft
Learning course repo is similar, and each contains the following folders:

   -

   Allfiles: This folder contains any supporting files for the labs. This
   is the same as the Allfiles folder that would appear on the virtual hard
   disk for virtual machines (VMs).
   -

   Build: This folder contains the Windows PowerShell script and supporting
   files for creating Word documents from the lab files that are in the
   Markdown format.
   -

   Instructions: This folder contains the lab files and LAK files, which
   are in the Markdown format.

You need all of these folders if you want to print the lab files.

**Comment by Trovalo** [comment]
The Build folder is still missing, why is the issue closed?
