### ISSUE TITLE
Module 2 - Exercise 4 - Task 7

### ISSUE THREAD

**Issue by tonycook2** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#9]
When the script is appended, it generates an error

The join predicate is not time bounded. JOIN operation between data streams requires specifying max time distances between matching events. Please add DATEDIFF to the JOIN condition.
Example:
SELECT input1.a, input2.b FROM input1 JOIN input2 ON DATEDIFF(minute, input1, input2) BETWEEN 0 AND 10

This is the script with the error

SELECT
C.VehicleRegistration,C.LocationLatitude,C.LocationLongitude,C.Time
INTO
StolenCarAlerts
FROM
StolenVehicleFeed1 C
JOIN
StolenVehicleData V
ON
C.VehicleRegistration = V.Vehicle
WHERE
V.Recovered = ""

Should there be a DATEDIFF statement in the script?

Regards

Tony Cook

**Comment by baolsen** [comment]
Add a Blob storage reference input to the TrafficAnalytics Stream Analytics job, with the following details:
Input alias: StolenVehicleData
